version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: smart-attendance-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: smart_attendance
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - smart-attendance-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/smart_attendance --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Backend
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: smart-attendance-backend
    restart: unless-stopped
    environment:
      MONGODB_URL: mongodb://admin:admin123@mongodb:27017/smart_attendance?authSource=admin
      SECRET_KEY: your-super-secret-key-change-in-production
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 1440
      CORS_ORIGINS: http://localhost:3000,http://localhost:5173,http://localhost
    ports:
      - "8000:8000"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - smart-attendance-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # React Frontend
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: smart-attendance-frontend
    restart: unless-stopped
    environment:
      VITE_API_BASE_URL: http://localhost:8000
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - smart-attendance-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3

volumes:
  mongodb_data:
    driver: local

networks:
  smart-attendance-network:
    driver: bridge
