name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE]: "
labels: ["enhancement", "feature-request"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! ✨
        Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: "I would like to see..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered
      placeholder: "An alternative approach could be..."

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the application would this feature affect?
      options:
        - Backend (FastAPI)
        - Frontend (React)
        - Database (MongoDB)
        - Authentication
        - QR Code System
        - Admin Dashboard
        - Instructor Dashboard
        - Trainee Dashboard
        - Documentation
        - DevOps/Deployment
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve experience
        - High - Critical for my use case
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe how this feature would be used
      placeholder: |
        As a [role], I want to [action] so that [benefit].
        
        Example scenarios:
        1. ...
        2. ...

  - type: textarea
    id: mockup
    attributes:
      label: Mockups/Examples
      description: If applicable, add mockups, wireframes, or examples from other applications
      placeholder: Drag and drop images here or paste URLs

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for similar feature requests before creating this one
          required: true
        - label: This feature aligns with the project's goals
          required: true
        - label: I am willing to submit a PR to implement this feature
          required: false
